export const Productos =[
    {
        id: 1,
        title: "Joy-Con",
        price: "10000",
        stock: 9,
        description: "Set de controles Joy-Con que cuenta con un diseño especial. El Joy-Con derecho está inspirado en la Espada Maestra, mientras que el izquierdo está inspirado en el escudo hyliano.",
        pictureUrl: 'https://assets.nintendo.com/image/upload/b_white,c_pad,f_auto,h_382,q_auto,w_573/ncom/en_US/hardware/switch/accessories/joy-con-l-r-the-legend-of-zelda-skyward-sword-hd-edition/joy-con-pkg?v=2022042115',
        category: 'accesorios',
    },
    {
        id: 2,
        title: "GamePad",
        price: "14900",
        stock: 5,
        description: "Pro Controller",
        pictureUrl: 'https://assets.nintendo.com/image/upload/f_auto,h_959,q_auto,w_1440/ncom/en_US/hardware/switch/accessories/nintendo-switch-pro-controller/promo',
        category: 'accesorios',
    },
    {
        id: 3,
        title: "Nintendo Switch",
        price: "78000",
        stock: 7,
        description: "Consola híbrida",
        pictureUrl: 'https://assets.nintendo.com/image/upload/f_auto,h_959,q_auto,w_1440/ncom/en_US/hardware/switch/nintendo-switch-new-package/promo',
        category: 'consolas',
    },
    {
      id: 4,
      title: "Nintendo Switch Oled",
      price: "90000",
      stock: 3,
      description: "Consola híbrida",
      pictureUrl: 'https://assets.nintendo.com/image/upload/f_auto,h_1162,q_auto,w_1440/ncom/en_US/switch/site-design-update/oled-package-white',
      category: 'consolas',
    },
    {
      id: 5,
      title: "Nintendo Switch Lite",
      price: "58000",
      stock: 5,
      description: "Consola portatil",
      pictureUrl: 'https://assets.nintendo.com/image/upload/f_auto,h_1194,q_auto,w_1440/ncom/en_US/hardware/switch/nintendo-switch-lite/promo',
      category: 'consolas',
    },
    {
      id: 6,
      title: "Nintendo Switch Carrying Case & Screen Protector",
      price: "78000",
      stock: 7,
      description: "Bolso transportador",
      pictureUrl: 'https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/bo_15px_solid_white/f_auto/q_auto/dpr_auto/c_scale,w_700/v1/ncom/en_US/products/accessories/nintendo-switch/system-cases-and-bags/nintendo-switch-carrying-case-screen-protector/114296-switch-carrying-case-black_silver-front-1200x675',
      category: 'accesorios',
    }
]